"use strict";
    class MenuHandler{
         constructor(){
             this.activeSubmenuId=null; this.currentSectionId='productosView';
             this.m = { 'menuProductos':'productosView', 'menuTablaPrecios':'priceTableView', 'menuJuegos':'juegosView', 'menuPagosPendientes': 'pagosPendientesView', 'menuRendicionCaja': 'rendicionCajaView', 'menuBackupGeneral': 'backupGeneralView', 'menuSeriesTable':'seriesTableView', 'menuCategoriesTable':'categoriesTableView', 'menuMarcasTable':'marcasView' };
             this.renderFunctions = { 'productosView': () => sistema.renderProductGridAndTable(), 'priceTableView': () => { const i=document.getElementById('priceTableSearchInput'); if(i&&i.value){i.value='';sistema.filterPriceTable('');} else {sistema.renderPriceTableOnly();} setTimeout(()=>i?.focus(),50); }, 'juegosView': () => sistema.renderJuegosTable(), 'pagosPendientesView': () => SistemaPagos.renderView(), 'rendicionCajaView': () => SistemaCaja.renderView(), 'backupGeneralView': () => { BackupManager.actualizarEstadoBackup(); }, 'seriesTableView': () => sistema.renderSeriesTable(), 'categoriesTableView': () => sistema.renderCategoryTable(), 'marcasView': () => sistema.renderMarcasTable() };
             this.initializeMenuEvents();
        }
         initializeMenuEvents(){ Object.entries(this.m).forEach(([menuId,sectionId])=>{ const target = document.getElementById(menuId); if(target) target.addEventListener('click',e=>{ e.preventDefault(); this.showSection(sectionId); }); }); document.querySelectorAll('.sidebar .menu-item > span').forEach(s=>{const u=s.nextElementSibling;if(u&&u.classList.contains('submenu')){s.removeAttribute('onclick');s.addEventListener('click',()=>this.toggleMenu(u.id));}}); }
         markActiveItem(menuId){ document.querySelectorAll('.sidebar .submenu-item, .sidebar .top-level-link').forEach(i=>i.classList.remove('active')); const activeLink = document.getElementById(menuId); if(activeLink){ activeLink.classList.add('active'); const parentSubmenu = activeLink.closest('.submenu'); if(parentSubmenu && !parentSubmenu.classList.contains('active')) { this.openSubmenu(parentSubmenu.id); } else if (activeLink.classList.contains('top-level-link') && this.activeSubmenuId) { this.closeSubmenu(this.activeSubmenuId); } } }
         toggleMenu(sId){const s=document.getElementById(sId);if(!s)return;const t=s.previousElementSibling,i=t?.querySelector('.toggle-icon');const a=s.classList.contains('active');if(!a&&this.activeSubmenuId&&this.activeSubmenuId!==sId)this.closeSubmenu(this.activeSubmenuId);s.classList.toggle('active');i?.classList.toggle('rotated',s.classList.contains('active'));this.activeSubmenuId=s.classList.contains('active')?sId:null;}
         openSubmenu(sId){const s=document.getElementById(sId);if(!s||s.classList.contains('active'))return;const t=s.previousElementSibling,i=t?.querySelector('.toggle-icon');if(this.activeSubmenuId&&this.activeSubmenuId!==sId)this.closeSubmenu(this.activeSubmenuId);s.classList.add('active');i?.classList.add('rotated');this.activeSubmenuId=sId;}
         closeSubmenu(sId){const s=document.getElementById(sId);if(!s)return;const t=s.previousElementSibling,i=t?.querySelector('.toggle-icon');s.classList.remove('active');i?.classList.remove('rotated');if(this.activeSubmenuId===sId)this.activeSubmenuId=null;}
         showSection(sId){ let found = false; document.querySelectorAll('.main-content > .content-wrapper').forEach(w=>{ if(w.id===sId){w.style.display='block'; w.classList.add('active'); found=true;} else{w.style.display='none'; w.classList.remove('active');} }); if(found){ this.currentSectionId=sId; this.markActiveItemBySectionId(sId); if (sId === 'pagosPendientesView' && !SistemaPagos.initialized) { SistemaPagos.init().then(() => { if (this.renderFunctions[sId]) requestAnimationFrame(this.renderFunctions[sId]); }); } else if (sId === 'rendicionCajaView' && !SistemaCaja.initialized) { SistemaCaja.init().then(() => { if (this.renderFunctions[sId]) requestAnimationFrame(this.renderFunctions[sId]); }); } else if (this.renderFunctions[sId]) { requestAnimationFrame(this.renderFunctions[sId]); } else { console.warn(`No render function defined for section: ${sId}`); } }else{ console.error(`Sección "${sId}" no encontrada.`); this.showSection('productosView'); } }
         markActiveItemBySectionId(sId){ const menuId = Object.keys(this.m).find(key => this.m[key] === sId); if(menuId) this.markActiveItem(menuId); }
    }
